[versions]
kotlin = "2.0.21"
agp = "8.7.3"
ksp = "2.0.21-1.0.28"
hilt = "2.57"
composeCompiler = "2.0.21"
room3ExternalAntlr = "3.0.0-alpha06"
junitKtx = "1.3.0"
ui = "1.11.2"
[libraries]
androidx-room3-external-antlr = { group = "androidx.room3", name = "room3-external-antlr", version.ref = "room3ExternalAntlr" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }
androidx-ui = { group = "androidx.compose.ui", name = "ui", version.ref = "ui" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }